name="cvm"

[database]
name="cvm"
user="postgres"
password="123456"
host="127.0.0.1"
port="5432"
schema="cvm"
# se necessário, informar o schema do banco em search_path. 'cvm' neste caso.
options="-c search_path=cvm,public"
